import type { Metadata } from 'next'
import './globals.css'
import ThemeRegistry from './components/ThemeRegistry'
import { Container } from '@mui/material'

export const metadata: Metadata = {
  title: 'Tag choices',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body>
          <Container
            sx={{
              height: "100vh",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            {children}
          </Container>
        </body>
      </ThemeRegistry>
    </html>
  )
}